config/routes.rb
Rails.application.routes.draw do

  resources :messages
  resources :super_users
  resources :reports
  #URLをcompanyから変更

  get '/description', to: 'tops#description'

  get 'search/member/:id', to: 'user_pages#index'
  post 'search/member/:id', to: 'company_offers#create'
  
  get 'search/company/:id', to: 'com_pages#index'

  get 'search/member/message/new/:id', to: 'messages#new'
  post 'search/member/message/new/:id', to: 'messages#create'
  get 'search/company/message/new/:id', to: 'messages#new'
  post 'search/company/message/new/:id', to: 'messages#create'
  
  get 'search/member' => 'search#member'
  get 'search/company' => 'search#company'
  get 'search/chat' => 'search#chat'

  post 'search/member' => 'search#member'
  post 'search/company' => 'search#company'
  post 'search/chat' => 'search#chat'

  get '/login_com', to: 'sessions_com#new'
  post '/login_com', to: 'sessions_com#create'
  delete '/logout_com', to: 'sessions_com#destroy'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  post '/login_chat', to: 'sessions_chat#create'
  get '/login_chat', to: 'sessions_chat#create'
  
  delete '/user_pages', to: 'company_offer#destroy'

  get '/com_pages/:id', to: 'com_pages#index'
  get '/user_pages/:id', to: 'user_pages#index'
  post '/com_pages/:id', to: 'com_pages#index'
  post '/user_pages/:id', to: 'user_pages#index'
  
  root to: 'tops#index'


  resources :users
  resources :user_pages, except: [:delete]
  resources :companys
  resources :com_pages
  resources :company_offers
  resources :chat_pages
  resources :chat_states
  resources :tops
end

app/models/chat.rb
class Chat < ApplicationRecord
end

app/models/chat_join_mem.rb
class ChatJoinMem < ApplicationRecord
    belongs_to :chat_page
end

app/models/chat_page.rb
class ChatPage < ApplicationRecord
    has_many :chat_states
    has_many :chat_join_mems
    validates :designer_id, presence: true, numericality: true
    validates :designer_name, presence: true, length: { maximum: 50}
    validates :max_mem, presence: true, numericality: true, inclusion: { in: 1..99999999}
    validates :theme, presence: true, length: { maximum: 200}
    validates :password, length: { maximum: 30}, format: {with: /\A[\w@-]*\z/}
    validates :update_date, presence: true
end

app/models/chat_state.rb
class ChatState < ApplicationRecord
    belongs_to :chat_page
    validates :remark_date, presence: true
    validates :mem_id, presence: true
    validates :mem_name, presence: true
    validates :sentence, presence: true, length: { maximum: 500} 
end

app/models/company.rb
class Company < ApplicationRecord
  has_secure_password
  validates :com_name, presence: true, length: {maximum: 50}
  validates :occupations, presence: true, length: {maximum: 100}
  validates :location, presence: true, length: {maximum: 50}
  validates :com_info, presence: true,uniqueness: true, length: {maximum: 30},format: {with:/\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
  validates :condition, presence: true, length: {maximum: 100}
  validates :salary, presence: true, numericality: true
  validates :bank, presence: true
end

app/models/company_offer.rb
class CompanyOffer < ApplicationRecord
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
    validates :mess, presence: true, length: {maximum:500}
end

app/models/offer_mail.rb
class OfferMail < ApplicationRecord
end

app/models/report.rb
class Report < ApplicationRecord
end

app/models/super_user.rb
class SuperUser < ApplicationRecord
    has_secure_password
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :mem_name, presence: true, length: {maximum: 20}
  validates :user_name,uniqueness: true, presence: true, length: {maximum: 10}
  validates :mem_info, presence: true, length: {maximum: 30},uniqueness: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :mem_birth, presence: true 
  validates :mem_gra, presence: true
  validates :des_occupation, presence: true, length: {maximum: 100}
  validates :des_location, presence: true, length: {maximum: 50}
  validates :password_digest, presence: true
  validates :univercity, length: {maximum: 20}
  validates :study, length: {maximum: 100}
  validates :deliver, length: {maximum: 10}
  validates :activity, length: {maximum: 50}
  validates :system_ex, length: {maximum: 50}
  validates :flame_ex,length: {maximum: 50}
end

app/controllers/com_pages_controller.rb
class ComPagesController < ApplicationController
  skip_before_action :login_required
  skip_before_action :login_com_required
  skip_before_action :login_super_user_required
  def index
    @chat_pages = ChatPage.all
    if current_company
      if params[:id].to_i == current_company.id || (params[:id] == nil)
        @company = current_company
        @company_offers = CompanyOffer.where(com_id: current_company)
      end
    elsif current_user
      @company = Company.find(params[:id])
      user_offers = CompanyOffer.where(mem_id: current_user)
      @use = user_offers.find_by(com_id: @company.id)
    else
      begin
        @company = Company.find(params[:id])
        if @company.admit == FALSE
          @company.admit = TRUE
          @company.save!
        end
      rescue
        redirect_back(fallback_location: root_path)
      end
    end
  end

  def show
  end

  def new
  end

  def edit
  end
end

app/helpers/chat_pages_helper.rb
module ChatPagesHelper
end

app/helpers/com_pages_helper.rb
module ComPagesHelper
end

app/helpers/companys_helper.rb
module CompanysHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/com_pages/edit.html.slim
h1 ComPages#edit
p Find me in app/views/com_pages/edit.html.slim

app/views/com_pages/index.html.slim
- if current_company
  = link_to  'ログアウト', logout_com_path, method: :delete,class: 'btn btn-primary'
  - if current_company.commitment == TRUE
    = link_to  '学生検索', "/search/member?s_word=&e_word=&des_occ=&des_loc=&quali=&univ=&lan_exp=", class: 'btn btn-primary'
    = link_to  'チャット検索', "/search/chat?s_word=&e_word=&category=&theme=&part=", class: 'btn btn-primary'
    - if params[:id] == nil || current_company.id == params[:id].to_i
      = link_to  'チャット作成', new_chat_page_url, class: 'btn btn-primary'
      = link_to  'メッセージ一覧', messages_path, class: 'btn btn-primary'
  = link_to 'アカウント情報を編集する',edit_company_path(current_company),class: 'btn btn-primary mr-3'
- elsif current_user
  = link_to  'ログアウト', logout_path, method: :delete,class: 'btn btn-primary'
  = link_to  '企業検索', "/search/company?s_word=&e_word=&occ=&loc=&system=&salary=&frame=&lang=", class: 'btn btn-primary'
  = link_to  'チャット検索', "/search/chat?s_word=&e_word=&category=&theme=&part=", class: 'btn btn-primary'
  = link_to  'マイページ', "/user_pages", class: 'btn btn-primary'
  -if @use
    - if @use.acc_flag == TRUE && @use.reaction == TRUE
     = link_to  'メッセージ送信', "/search/company/message/new/" + @company.id.to_s, class: 'btn btn-primary'
- elsif current_super_user
  = link_to  'マイページ', super_users_path, class: 'btn btn-primary'
  = link_to 'アカウント削除', super_user_path, method: :delete, data: { confirm:"アカウント#{params[:id]}をデータベースから削除します。よろしいですか？"}, type:'button', class: 'btn btn-sm btn-danger'
- else
  = link_to  'TOP', "/", class: 'btn btn-primary'

h1 企業情報

.mb-3
table.table.table-hover
  thead.thead-default
    tr
      th = Company.human_attribute_name(:会社名)
      th = Company.human_attribute_name(:職種)
      th = Company.human_attribute_name(:勤務地)
      th = Company.human_attribute_name(:開発言語)
      th = Company.human_attribute_name(:フレームワーク)
      th = Company.human_attribute_name(:開発体制)
      th = Company.human_attribute_name(:初任給)
      th = Company.human_attribute_name(:オファー残高)
  tbody
    tr
      td= @company.com_name
      td= @company.occupations
      td= @company.location
      td= @company.lang
      td= @company.frame
      td= @company.system_ex
      td= @company.salary
      td= @company.balance
    tr
      th = Company.human_attribute_name(:労働条件)
  tbody
    tr
      td= @company.condition
    
    tr
      th = Company.human_attribute_name(:アピールポイント)
  tbody
    tr
      td= @company.appeal
      tr
      th = User.human_attribute_name(:オファー一覧)
      - if @company_offers
        - @company_offers.each do |offer|
          tr
            th = CompanyOffer.human_attribute_name(:送った学生氏名)
            th = CompanyOffer.human_attribute_name(:送ったユーザ名)
          tbody
            tr
              - user = User.find(offer.mem_id)
              td= user.mem_name
              td= user.user_name
          
              - if offer.acc_flag == TRUE && offer.reaction == TRUE


                td= '承認済み'
                td= link_to '学生ページへ', user_page_path(offer.mem_id),class: 'btn btn-primary mr-3'
              - if offer.acc_flag == TRUE && offer.reaction == FALSE
                td= '辞退されました'
              - if offer.acc_flag == FALSE
                td= '未承認'
                td= link_to '学生ページへ', user_page_path(offer.mem_id),class: 'btn btn-primary mr-3'

.mb-3
table.table.table-hover
  thead.thead-default
    tr
      th 作成したディスカッション一覧
      th パスワード
      th 更新日時
      th
  tbody
    - @chat_pages.each do |chat_page|
      - if chat_page.designer_id == @company.id
        form action=login_chat_path method="GET"
          tr
            |
            input name="id" type="hidden" value="#{chat_page.id}"/ 
            td
              | #{chat_page.theme}
            - if chat_page.readable
              td　未設定
            - else
              td
                |
                input name="password" style=("width:300px; height:30px") type="text"/
            td #{chat_page.update_date}
            td= button_to "チャットページへ",login_chat_path,class: 'btn btn-primary mr-3'
            
    tr
      th = Company.human_attribute_name(:採用ページurl)
  tbody
    tr
      td= @company.adoption

app/views/com_pages/new.html.slim
h1 ComPages#new
p Find me in app/views/com_pages/new.html.slim

app/views/com_pages/show.html.slim
h1 ComPages#show
p Find me in app/views/com_pages/show.html.slim