config/routes.rb
Rails.application.routes.draw do

  resources :messages
  resources :super_users
  resources :reports
  #URLをcompanyから変更

  get '/description', to: 'tops#description'

  get 'search/member/:id', to: 'user_pages#index'
  post 'search/member/:id', to: 'company_offers#create'
  
  get 'search/company/:id', to: 'com_pages#index'

  get 'search/member/message/new/:id', to: 'messages#new'
  post 'search/member/message/new/:id', to: 'messages#create'
  get 'search/company/message/new/:id', to: 'messages#new'
  post 'search/company/message/new/:id', to: 'messages#create'
  
  get 'search/member' => 'search#member'
  get 'search/company' => 'search#company'
  get 'search/chat' => 'search#chat'

  post 'search/member' => 'search#member'
  post 'search/company' => 'search#company'
  post 'search/chat' => 'search#chat'

  get '/login_com', to: 'sessions_com#new'
  post '/login_com', to: 'sessions_com#create'
  delete '/logout_com', to: 'sessions_com#destroy'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  post '/login_chat', to: 'sessions_chat#create'
  get '/login_chat', to: 'sessions_chat#create'
  
  delete '/user_pages', to: 'company_offer#destroy'

  get '/com_pages/:id', to: 'com_pages#index'
  get '/user_pages/:id', to: 'user_pages#index'
  post '/com_pages/:id', to: 'com_pages#index'
  post '/user_pages/:id', to: 'user_pages#index'
  
  root to: 'tops#index'


  resources :users
  resources :user_pages, except: [:delete]
  resources :companys
  resources :com_pages
  resources :company_offers
  resources :chat_pages
  resources :chat_states
  resources :tops
end

app/models/chat_page.rb
class ChatPage < ApplicationRecord
    has_many :chat_states
    has_many :chat_join_mems
    validates :designer_id, presence: true, numericality: true
    validates :designer_name, presence: true, length: { maximum: 50}
    validates :max_mem, presence: true, numericality: true, inclusion: { in: 1..99999999}
    validates :theme, presence: true, length: { maximum: 200}
    validates :password, length: { maximum: 30}, format: {with: /\A[\w@-]*\z/}
    validates :update_date, presence: true
end

app/controllers/chat_pages_controller.rb
class ChatPagesController < ApplicationController
  skip_before_action :login_required
  skip_before_action :login_com_required
  skip_before_action :login_super_user_required
  def index
    @chat_pages = ChatPage.all
  end

  def show
    @chat_page = ChatPage.find(params[:id])
    @chat_states = @chat_page.chat_states.all
    @chat_join_mems = @chat_page.chat_join_mems.all
    @chat_join_mem =  @chat_page.chat_join_mems.new
    @chat_state = ChatState.new
    @report = Report.new

    if current_company
      @report_man = current_company.id
    elsif current_user
      @report_man = current_user.id
    end

    /参加ボタンが押されたとき/ 
    if params[:join_chat]
      if @chat_page.join_mem < @chat_page.max_mem
        @chat_page.join_mem += 1
        if current_user
          @chat_join_mem.mem_id = current_user.id
          @chat_join_mem.mem_name = current_user.user_name    
        elsif current_company
          @chat_join_mem.mem_id = current_company.id
          @chat_join_mem.mem_name = current_company.com_name
        end        
        if @chat_page.join_mem >= @chat_page.max_mem
          @chat_page.rec = false
        end
        @chat_page.save
        redirect_to chat_page_path(@chat_page), notice: "チャットに参加しました" and return
      else
        redirect_to chat_page_path(@chat_page), notice: "上限人数です" and return
      end
    end

    /新規参加者かを判定する/
    @new_mem = true
    @chat_join_mems.each do |chat_join_mem|
      if current_user
        if current_user.user_name == chat_join_mem.mem_name
          @new_mem = false
        end
      elsif current_company
        if current_company.com_name == chat_join_mem.mem_name
          @new_mem = false
        end
      end
    end


    session[:chat_page_id] = @chat_page.id
  end

  def new
    @chat_page = ChatPage.new
  end

  def create

    @chat_page = ChatPage.new(chat_page_params)

    if @chat_page.max_mem.nil?
      redirect_to new_chat_page_path, notice: "上限人数が入力されていません" and return
    end 

    if @chat_page.start_date.nil?
      redirect_to new_chat_page_path, notice: "開催日時が入力されていません" and return
    end

    unless @chat_page.finish_date.nil?
      if @chat_page.start_date > @chat_page.finish_date
          redirect_to new_chat_page_path, notice: "終了日時が開催日時より前になっています" and return
      end
    end
    
    if @chat_page.theme.empty?
      redirect_to new_chat_page_path, notice: "テーマが入力されていません" and return
    end 


    @chat_join_mem =  @chat_page.chat_join_mems.new
    if current_user
      @chat_page.designer_id = current_user.id
      @chat_page.designer_name = current_user.user_name
      @chat_page.designer_val = "user"
      @chat_join_mem.mem_id = current_user.id
      @chat_join_mem.mem_name = current_user.user_name
    elsif current_company
      @chat_page.designer_id = current_company.id
      @chat_page.designer_name = current_company.com_name
      @chat_page.designer_val = "com"
      @chat_join_mem.mem_id = current_company.id
      @chat_join_mem.mem_name = current_company.com_name
    end
    @chat_page.join_mem += 1

    if @chat_page.max_mem >= 2
      @chat_page.rec = true
    else
      @chat_page.rec = false
    end

    @chat_page.period = Date.today

    if !@chat_page.password.blank?
      @chat_page.readable = false
    end

    @chat_page.update_date = Date.today

    unless @chat_page.finish_date.nil?
      if @chat_page.start_date > @chat_page.finish_date
          redirect_to new_chat_page_path, notice: "終了日時が開催日時より前になっています" and return
      end
    end
 

    if @chat_page.save
      redirect_to chat_page_path(@chat_page), notice: "チャットを作成しました。"
    else
      redirect_to new_chat_page_path, notice: "入力された項目に誤りがあります"
    end
  end

  def remark

  end

  private
  def chat_page_params
    params.require(:chat_page).permit(:max_mem, :start_date, :finish_date, :password, :readable, :theme)
  end

end

app/helpers/chat_pages_helper.rb
module ChatPagesHelper
end

app/views/chat_pages/index.html.slim
h1 チャット一覧


.mb-3
table.table.table-hover
  thead.thead-default
    tr
      th チャットid
      th テーマ
      th パスワード
      th　      
  tbody
    - @chat_pages.each do |chat|
      form action=login_chat_path method="GET"
        tr
          td
            | #{chat.id}
            input name="id" type="hidden" value="#{chat.id}"/ 
          - if chat.readable 
            td
              | #{chat.theme}
            td　未設定
          - else
            td 非公開
            td
              |
              input name="password" style=("width:300px; height:30px") type="text"/
          td= button_to "参加する"

app/views/chat_pages/new.html.slim
h1 チャット作成
- if current_user 
  = link_to  'マイページ', "/user_pages", class: 'btn btn-primary'
- elsif current_company
  = link_to  'マイページ', "/com_pages",class: 'btn btn-primary'
  
= form_with model: @chat_page, local: true do |f|
  .form-group
    = f.label :max_mem, '上限人数（必須）'
    = f.number_field :max_mem, class: 'form-controll', id: 'chat_page_max_mem'
  .form-group
    = f.label :start_date, '開催日時（必須）'
    = f.date_field :start_date, class: 'form-controll', id: 'chat_page_start_date'
  .form-group
    = f.label :finish_date, '終了日時'
    = f.date_field :finish_date, class: 'form-controll', id: 'chat_page_finish_date'
  - if current_company
    .form-group
      = f.label :password, 'パスワード'
      = f.text_field :password, class: 'form-controll', placeholder: '半角英数字・記号のみ', id: 'chat_page_password'

  .form-group
    = f.label :theme, 'テーマ（必須）'
    = f.text_area :theme, rows: 3, cols: 40, class: 'form-controll', id: 'chat_page_theme'
  = f.submit '作成', class: 'btn btn-primary'

app/views/chat_pages/show.html.slim
- if current_user
  = link_to 'マイページ', user_page_path(current_user.id),class: 'btn btn-primary mr-3'
- elsif current_company
  = link_to 'マイページ', com_page_path(current_company.id),class: 'btn btn-primary mr-3'
- elsif current_super_user
  = link_to 'マイページ', super_users_path,class: 'btn btn-primary mr-3'
- else
  = link_to 'TOP',"/", class: 'btn btn-primary'

h1= @chat_page.theme

p 参加人数
= @chat_page.join_mem
  
p 上限人数
= @chat_page.max_mem

p 更新日時
= @chat_page.update_date


.mb-3
table.table.table-hover
 thead.thead-default
   tr[style="width 900px"]
     th 発言内容
     th 発言者
     th      
     th     
 tbody
   - @chat_states.each do |chat_state|
     tr
       td= chat_state.sentence
       - if !User.where(id: chat_state.mem_id).empty? || !Company.where(id: chat_state.mem_id).empty?         
         td= chat_state.mem_name
         - if current_user || current_company
           - if chat_state.mem_val == "com" && (current_user || chat_state.mem_name == current_company.com_name)
             td= link_to 'マイページ', com_page_path(chat_state.mem_id),class: 'btn btn-primary mr-3'
           - elsif chat_state.mem_val == "user"
             td= link_to 'マイページ', user_page_path(chat_state.mem_id),class: 'btn btn-primary mr-3'
         - if current_user && (current_user.id != chat_state.mem_id)
           form action=reports_path method="POST"
             td= link_to '通報', reports_path(report_chat: @chat_page.id, report_man: @report_man, reported_man: chat_state.mem_id), method: :create, data: { confirm:"通報します。よろしいですか？"}, type:'button', class: 'btn btn-sm btn-danger'
         - else
           td
       - else
         td 削除済みアカウント
         td 
         td

- if current_user || (current_company && (current_company.com_name == @chat_page.designer_name))
  - if@new_mem
    form action=chat_page_path method="GET"
      td
        |
        input name="join_chat" type="hidden" value="true"/
      td= button_to "参加する"
  - else 
    = form_with model: @chat_state, local: true do |f|
      .form-group
      = f.text_area :sentence, cols: 150, class: 'form-controll', id: 'chat_state_sentence'
      = f.submit '送信', class: 'btn btn-primary'
             