config/routes.rb
Rails.application.routes.draw do

  resources :messages
  resources :super_users
  resources :reports
  #URLをcompanyから変更

  get '/description', to: 'tops#description'

  get 'search/member/:id', to: 'user_pages#index'
  post 'search/member/:id', to: 'company_offers#create'
  
  get 'search/company/:id', to: 'com_pages#index'

  get 'search/member/message/new/:id', to: 'messages#new'
  post 'search/member/message/new/:id', to: 'messages#create'
  get 'search/company/message/new/:id', to: 'messages#new'
  post 'search/company/message/new/:id', to: 'messages#create'
  
  get 'search/member' => 'search#member'
  get 'search/company' => 'search#company'
  get 'search/chat' => 'search#chat'

  post 'search/member' => 'search#member'
  post 'search/company' => 'search#company'
  post 'search/chat' => 'search#chat'

  get '/login_com', to: 'sessions_com#new'
  post '/login_com', to: 'sessions_com#create'
  delete '/logout_com', to: 'sessions_com#destroy'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  post '/login_chat', to: 'sessions_chat#create'
  get '/login_chat', to: 'sessions_chat#create'
  
  delete '/user_pages', to: 'company_offer#destroy'

  get '/com_pages/:id', to: 'com_pages#index'
  get '/user_pages/:id', to: 'user_pages#index'
  post '/com_pages/:id', to: 'com_pages#index'
  post '/user_pages/:id', to: 'user_pages#index'
  
  root to: 'tops#index'


  resources :users
  resources :user_pages, except: [:delete]
  resources :companys
  resources :com_pages
  resources :company_offers
  resources :chat_pages
  resources :chat_states
  resources :tops
end

app/models/chat.rb
class Chat < ApplicationRecord
end

app/models/chat_join_mem.rb
class ChatJoinMem < ApplicationRecord
    belongs_to :chat_page
end

app/models/chat_page.rb
class ChatPage < ApplicationRecord
    has_many :chat_states
    has_many :chat_join_mems
    validates :designer_id, presence: true, numericality: true
    validates :designer_name, presence: true, length: { maximum: 50}
    validates :max_mem, presence: true, numericality: true, inclusion: { in: 1..99999999}
    validates :theme, presence: true, length: { maximum: 200}
    validates :password, length: { maximum: 30}, format: {with: /\A[\w@-]*\z/}
    validates :update_date, presence: true
end

app/models/chat_state.rb
class ChatState < ApplicationRecord
    belongs_to :chat_page
    validates :remark_date, presence: true
    validates :mem_id, presence: true
    validates :mem_name, presence: true
    validates :sentence, presence: true, length: { maximum: 500} 
end

app/models/company.rb
class Company < ApplicationRecord
  has_secure_password
  validates :com_name, presence: true, length: {maximum: 50}
  validates :occupations, presence: true, length: {maximum: 100}
  validates :location, presence: true, length: {maximum: 50}
  validates :com_info, presence: true,uniqueness: true, length: {maximum: 30},format: {with:/\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
  validates :condition, presence: true, length: {maximum: 100}
  validates :salary, presence: true, numericality: true
  validates :bank, presence: true
end

app/models/company_offer.rb
class CompanyOffer < ApplicationRecord
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
    validates :mess, presence: true, length: {maximum:500}
end

app/models/offer_mail.rb
class OfferMail < ApplicationRecord
end

app/models/report.rb
class Report < ApplicationRecord
end

app/models/super_user.rb
class SuperUser < ApplicationRecord
    has_secure_password
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :mem_name, presence: true, length: {maximum: 20}
  validates :user_name,uniqueness: true, presence: true, length: {maximum: 10}
  validates :mem_info, presence: true, length: {maximum: 30},uniqueness: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :mem_birth, presence: true 
  validates :mem_gra, presence: true
  validates :des_occupation, presence: true, length: {maximum: 100}
  validates :des_location, presence: true, length: {maximum: 50}
  validates :password_digest, presence: true
  validates :univercity, length: {maximum: 20}
  validates :study, length: {maximum: 100}
  validates :deliver, length: {maximum: 10}
  validates :activity, length: {maximum: 50}
  validates :system_ex, length: {maximum: 50}
  validates :flame_ex,length: {maximum: 50}
end

app/controllers/super_users_controller.rb
# coding: utf-8
class SuperUsersController < ApplicationController
  skip_before_action :login_required
  skip_before_action :login_com_required

  def index
    
    @report = Report.all
    @company = Company.where("admit = TRUE").where("commitment = FALSE")
    #@report.each 通報崎のurlしてい

    @additions = Company.where(balance: 0)  
    
    
  end

  def show



  end

  def new
    @messages = Message.new
  end

  
  def destroy
    if (params[:id].to_i / 1000000000)==1
      user = User.find(params[:id])
      company_offers = CompanyOffer.where(mem_id: user.id)
      company_offers.each do |offer|
        offer.destroy
      end
      reported_mans = Report.where(reported_man: user.id)
      reported_mans.each do |reported_man|
        reported_man.destroy
      end
      report_mans = Report.where(report_man: user.id)
      report_mans.each do |report_man|
        report_man.destroy
      end
      user.destroy
      redirect_to super_users_url, notice: "アカウントID[#{params[:id]}]を削除しました"
    elsif (params[:id].to_i / 1000000000)==2
      com = Company.find(params[:id])
      company_offers = CompanyOffer.where(com_id: com.id)
      company_offers.each do |offer|
        offer.destroy
      end
      reported_mans = Report.where(reported_man: com.id)
      reported_mans.each do |reported_man|
        reported_man.destroy
      end
      report_mans = Report.where(report_man: com.id)
      report_mans.each do |report_man|
        report_man.destroy
      end
      com.destroy
      redirect_to super_users_url, notice: "アカウントID[#{params[:id]}]を削除しました"
    end
  end

end

app/helpers/chat_pages_helper.rb
module ChatPagesHelper
end

app/helpers/com_pages_helper.rb
module ComPagesHelper
end

app/helpers/companys_helper.rb
module CompanysHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/super_users_helper.rb
module SuperUsersHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/super_users/_form.html.slim
= form_for @super_user do |f|
  - if @super_user.errors.any?
    #error_explanation
      h2 = "#{pluralize(@super_user.errors.count, "error")} prohibited this super_user from being saved:"
      ul
        - @super_user.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :super_user_id
    = f.number_field :super_user_id
  .field
    = f.label :super_user_password
    = f.text_field :super_user_password
  .field
    = f.label :super_user_name
    = f.number_field :super_user_name
  .actions = f.submit

app/views/super_users/edit.html.slim
h1 Editing super_user

== render 'form'

=> link_to 'Show', @super_user
'|
=< link_to 'Back', super_users_path

app/views/super_users/index.html.slim
h1 管理者のページ
= link_to  'ログアウト', logout_path, method: :delete,  class: 'btn btn-primary', style: 'position:relative; top:-10%; left:50%; overflow: hidden'
= link_to  '企業検索', "/search/company?s_word=&e_word=&occ=&loc=&system=&salary=&frame=&lang=", {class: 'btn btn-primary', style: 'position:relative; top:0%; left:50%; overflow: hidden'}
= link_to  '学生検索', "/search/member?s_word=&e_word=&des_occ=&des_loc=&quali=&univ=&lan_exp=",  {class: 'btn btn-primary', style: 'position:relative; top:10%; left:50%; overflow: hidden'}
= link_to  'チャット検索', "/search/chat?s_word=&e_word=&category=&theme=&part=",  {class: 'btn btn-primary', style: 'position:relative; top:20%; left:50%; overflow: hidden'}

br
br
br
p 通報一覧
.mb-3

table.table.table-hover
  thead.thead-default
    tr
      th = Report.human_attribute_name(:通報ID)
      th = Report.human_attribute_name(:通報した人)
      th = Report.human_attribute_name(:通報された人)
      th = Report.human_attribute_name(:通報が起きたチャット)
  tbody
    - @report.each do |report|
      tr
        td= report.id
        -if (report.report_man.to_i / 1000000000)==1
          - user = User.find(report.report_man)
          td= link_to user.user_name, "/search/member/#{report.report_man}"
        -else
          - com = Company.find(report.report_man)
          td= link_to com.com_name, "/search/company/#{report.report_man}"          
        -if (report.reported_man.to_i / 1000000000)==1
          - user = User.find(report.reported_man)
          td= link_to user.user_name, "/search/member/#{report.reported_man}"
        -else
          - com = Company.find(report.reported_man)
          td= link_to com.com_name, "/search/company/#{report.reported_man}"          
        - chat = ChatPage.find(report.report_chat)
        td= link_to chat.theme, "/chat_pages/#{report.report_chat}"
        td= link_to '確認', report, method: :delete, data: { confirm:"通報#{report.id}をデータベースから削除します。よろしいですか？"}, type:'button', class: 'btn btn-sm btn-danger'
br
br
table.table.table-hover
 thead.thead-default
   tr
     th = Company.human_attribute_name(:新着企業)
 tbody
   - @company.each do |company|
     tr
       td= link_to company.com_name,"/search/company/#{company.id}"
       td= link_to '確認完了',company,method: :delete, type:'button', class: 'btn btn-sm btn-primary'
br
br
table.table.table-hover
  thead.thead-default
    tr
      th = Company.human_attribute_name(:オファー残高が０の企業ID)
      th = Company.human_attribute_name(:企業名) 
  tbody
    - @additions.each do |addition|
      tr
        td= addition.id
        td= addition.com_name
        td= link_to 'オファー追加',edit_company_offer_path(addition),data:{ confirm:"オファーを追加しますか?"},class: 'btn btn-primary mr-3'

app/views/super_users/new.html.slim
h1 New super_user

== render 'form'

= link_to 'Back', super_users_path

app/views/super_users/show.html.slim
p#notice = notice

p
  strong Super user:
  = @super_user.super_user_id
p
  strong Super user password:
  = @super_user.super_user_password
p
  strong Super user name:
  = @super_user.super_user_name

=> link_to 'Edit', edit_super_user_path(@super_user)
'|
=< link_to 'Back', super_users_path