config/routes.rb
Rails.application.routes.draw do

  resources :messages
  resources :super_users
  resources :reports
  #URLをcompanyから変更

  get '/description', to: 'tops#description'

  get 'search/member/:id', to: 'user_pages#index'
  post 'search/member/:id', to: 'company_offers#create'
  
  get 'search/company/:id', to: 'com_pages#index'

  get 'search/member/message/new/:id', to: 'messages#new'
  post 'search/member/message/new/:id', to: 'messages#create'
  get 'search/company/message/new/:id', to: 'messages#new'
  post 'search/company/message/new/:id', to: 'messages#create'
  
  get 'search/member' => 'search#member'
  get 'search/company' => 'search#company'
  get 'search/chat' => 'search#chat'

  post 'search/member' => 'search#member'
  post 'search/company' => 'search#company'
  post 'search/chat' => 'search#chat'

  get '/login_com', to: 'sessions_com#new'
  post '/login_com', to: 'sessions_com#create'
  delete '/logout_com', to: 'sessions_com#destroy'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  post '/login_chat', to: 'sessions_chat#create'
  get '/login_chat', to: 'sessions_chat#create'
  
  delete '/user_pages', to: 'company_offer#destroy'

  get '/com_pages/:id', to: 'com_pages#index'
  get '/user_pages/:id', to: 'user_pages#index'
  post '/com_pages/:id', to: 'com_pages#index'
  post '/user_pages/:id', to: 'user_pages#index'
  
  root to: 'tops#index'


  resources :users
  resources :user_pages, except: [:delete]
  resources :companys
  resources :com_pages
  resources :company_offers
  resources :chat_pages
  resources :chat_states
  resources :tops
end

app/models/chat.rb
class Chat < ApplicationRecord
end

app/models/chat_join_mem.rb
class ChatJoinMem < ApplicationRecord
    belongs_to :chat_page
end

app/models/chat_page.rb
class ChatPage < ApplicationRecord
    has_many :chat_states
    has_many :chat_join_mems
    validates :designer_id, presence: true, numericality: true
    validates :designer_name, presence: true, length: { maximum: 50}
    validates :max_mem, presence: true, numericality: true, inclusion: { in: 1..99999999}
    validates :theme, presence: true, length: { maximum: 200}
    validates :password, length: { maximum: 30}, format: {with: /\A[\w@-]*\z/}
    validates :update_date, presence: true
end

app/models/chat_state.rb
class ChatState < ApplicationRecord
    belongs_to :chat_page
    validates :remark_date, presence: true
    validates :mem_id, presence: true
    validates :mem_name, presence: true
    validates :sentence, presence: true, length: { maximum: 500} 
end

app/models/company.rb
class Company < ApplicationRecord
  has_secure_password
  validates :com_name, presence: true, length: {maximum: 50}
  validates :occupations, presence: true, length: {maximum: 100}
  validates :location, presence: true, length: {maximum: 50}
  validates :com_info, presence: true,uniqueness: true, length: {maximum: 30},format: {with:/\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
  validates :condition, presence: true, length: {maximum: 100}
  validates :salary, presence: true, numericality: true
  validates :bank, presence: true
end

app/models/company_offer.rb
class CompanyOffer < ApplicationRecord
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
    validates :mess, presence: true, length: {maximum:500}
end

app/models/offer_mail.rb
class OfferMail < ApplicationRecord
end

app/models/report.rb
class Report < ApplicationRecord
end

app/models/super_user.rb
class SuperUser < ApplicationRecord
    has_secure_password
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :mem_name, presence: true, length: {maximum: 20}
  validates :user_name,uniqueness: true, presence: true, length: {maximum: 10}
  validates :mem_info, presence: true, length: {maximum: 30},uniqueness: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :mem_birth, presence: true 
  validates :mem_gra, presence: true
  validates :des_occupation, presence: true, length: {maximum: 100}
  validates :des_location, presence: true, length: {maximum: 50}
  validates :password_digest, presence: true
  validates :univercity, length: {maximum: 20}
  validates :study, length: {maximum: 100}
  validates :deliver, length: {maximum: 10}
  validates :activity, length: {maximum: 50}
  validates :system_ex, length: {maximum: 50}
  validates :flame_ex,length: {maximum: 50}
end

app/controllers/companys_controller.rb
# coding: utf-8
class CompanysController < ApplicationController
  skip_before_action :login_required
  skip_before_action :login_com_required
  skip_before_action :login_super_user_required
  def new
    @company = Company.new
  end

  def create
    @company = Company.new(company_params)

    if @company.save
      @company.id = @company.id + 2000000000
      @company.admit = FALSE
      @company.commitment = FALSE
      @company.save

      begin
        InquiryMailer.send_mail(@company).deliver_now
        redirect_to companys_path, notice:"メールが送信されました。内容を確認してください"
      rescue
        Company.where("id = ?", @company.id.to_i).delete_all
        redirect_to new_company_path, notice:"メールが送れませんでした"
      end
    else
      render :new, notice:"項目に誤りがあります"  
    end
  end

  
  def edit
    @company = current_company
  end

  def update
    @company = current_company
    if @company.update(company_params)
      redirect_to com_pages_path, notice: "更新完了"
    else
      render :edit    
    end
  end

  def show
  end

  def index
    
  end

  def destroy
    company = Company.find(params[:id])
    company.commitment = TRUE
    company.save
    redirect_to super_users_url, notice: "承認しました"
  end

  private
  def company_params
    params.require(:company).permit(:com_name,:occupations,:location,:com_info,:condition,:salary,:password,:password_confirmation,:frame,:lang,:adoption,:system_ex,:appeal,:bank)
  end
  
end

app/helpers/chat_pages_helper.rb
module ChatPagesHelper
end

app/helpers/com_pages_helper.rb
module ComPagesHelper
end

app/helpers/companys_helper.rb
module CompanysHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/user_pages_helper.rb
module UserPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/companys/_form.html.slim
= link_to 'TOPページへ',"/", class: 'btn btn-primary'

= form_with model: company,local: true do |f|
  .form-group
    = f.label :com_name
    = f.text_field :com_name, class: 'form-control', id: 'company_com_name'
  .form-group
    = f.label :occupations
    = f.text_field :occupations, class: 'form-control', id: 'company_occupations'
  .form-group
    = f.label :com_info
    = f.text_field :com_info, class: 'form-control', id: 'company_com_info'
  .form-group
    = f.label :"勤務地"
    = f.select :location,[["千葉","千葉"],["茨城","茨城"]], id: 'company_location'
  .form-group
    = f.label :salary
    = f.number_field :salary, id: 'company_salary'
  .form-group
    = f.label :condition
    = f.text_field :condition, class: 'form-control', id: 'company_condition'
  .form-group 
    = f.label :appeal
    = f.text_area :appeal, class: 'form-control', id: 'company_appeal'
  .form-group
    = f.label :password, 'パスワード'
    = f.password_field :password, class: 'form-control', id: 'company_password'
  .form-group
    = f.label :password_confirmation, 'パスワード確認'
    = f.password_field :password_confirmation, class: 'form-control', id: 'company_password_confirmation'
  = f.submit nil, class: 'btn btn-primay'

app/views/companys/edit.html.slim
h1 企業修正画面
.nav.justify-content-end
  =link_to 'マイページへ',com_pages_path, class: 'btn btn-primary'

= form_with model: @company,local: true do |f|
  .form-group
    = f.label :"企業名(必須)"
    = f.text_field :com_name, class: 'form-control', id: 'company_com_name'
  .form-group
     = f.label :"職種(必須)"
     = f.select :occupations,[["システムエンジニア","システムエンジニア"],["プログラマ","プログラマ"],["Webエンジニア","Webエンジニア"],["データベースエンジニア","データベースエンジニア"]]
  .form-group
     = f.label :"メールアドレス(必須)"
     = f.text_field :com_info, class: 'form-control', id: 'company_com_info'
  .form-group
    = f.label :"勤務地(必須)"
    = f.select :location,[["千葉","千葉"],["茨城","茨城"],["東京","東京"],["埼玉","埼玉"],["神奈川","神奈川"],["神奈川","神奈川"],["群馬","群馬"],["栃木","栃木"]], id: 'company_location'
  .form-group
    = f.label :"初任給(必須)"
    = f.number_field :salary, id: 'company_salary'
  .form-group
    = f.label :"労働条件(必須)"
    = f.text_field :condition, class: 'form-control', id: 'company_condition'
  .form-group
    = f.label :"アピールポイント(必須)"
    = f.text_area :appeal, class: 'form-control', id: 'company_appeal'
  
  .form-group
    = f.label :"会社口座番号(必須項目)"
    = f.text_area :bank, class: 'form-control', id: 'company_bank'

  .form-group
    = f.label :"主な開発言語"
    = f.select :lang,[["-",""],["C言語","C言語"],["Java","Java"],["C++","C++"],["Ruby","Ruby"],["Python","Python"]]
  .form-group
    = f.label :"主な経験開発体制"
    = f.select :system_ex,[["-",""],["ウォーターフォールモデル","ウォーターフォールモデル"],["プロトタイピングモデル","プロトタイピングモデル"],["スパイラルモデル","スパイラルモデル"],["アジャイル開発モデル","アジャイル開発モデル"]]
  .form-group
    = f.label :"主なフレームワーク"
    = f.select :frame,[["-",""],["Ruby on Rails","Ruby on Rails"],["CakePHP","CakePHP"],["Spring","Spring"],["jQuiry","jQuiry"],["Bootstrap","Bootstrap"]]
  .form-group
    = f.label :"採用ページのURL"
    = f.text_area :adoption, class: 'form-control', id: 'company_adoption'


  = f.submit nil, class: 'btn btn-primay'

app/views/companys/index.html.slim
h1 登録完了

= link_to 'TOPページへ',"/", class: 'btn btn-primary'
= link_to  '企業でログイン', login_com_path, class: 'btn btn-primary'

p メールを確認してください

app/views/companys/new.html.slim
- if @company.errors.present?
  ul#error_explanation
  - @company.errors.full_messages.each do |message|
    li = message

h1 企業登録画面
= link_to 'TOPページへ',"/", class: 'btn btn-primary'
= form_with model: @company, url: companys_path, local: true do |f|
  .form-group
    = f.label :"企業名(必須)"
    = f.text_field :com_name, class: 'form-control', id: 'company_com_name'
  .form-group
    = f.label :"職種(必須)"
    = f.select :occupations,[["システムエンジニア","システムエンジニア"],["プログラマ","プログラマ"],["Webエンジニア","Webエンジニア"],["データベースエンジニア","データベースエンジニア"]]
  .form-group
    = f.label :"メールアドレス(必須)"
    = f.text_field :com_info, class: 'form-control', id: 'company_com_info'
  .form-group
    = f.label :"勤務地(必須)"
    = f.select :location,[["千葉","千葉"],["茨城","茨城"],["東京","東京"],["埼玉","埼玉"],["神奈川","神奈川"],["群馬","群馬"],["栃木","栃木"]], id: 'company_location'
  .form-group
    = f.label :"初任給(必須)"
    = f.number_field :salary, id: 'company_salary'
  .form-group
    = f.label :"労働条件(必須)"
    = f.text_field :condition, class: 'form-control', id: 'company_condition'
  .form-group
    = f.label :"アピールポイント(必須)"
    = f.text_area :appeal, class: 'form-control', id: 'company_appeal'
  .form-group
    = f.label :"パスワード(必須項目)"
    = f.password_field :password, class: 'form-control', id: 'company_password'
  .form-group
    = f.label :"パスワード確認(必須項目)"
    = f.password_field :password_confirmation, class: 'form-control', id: 'company_password_confirmation'
  .form-group
    = f.label :"会社口座番号(必須項目)"
    = f.text_area :bank, class: 'form-control', id: 'company_bank'


  .form-group
    = f.label :"主な開発言語"
    = f.select :lang,[["-",""],["C言語","C言語"],["Java","Java"],["C++","C++"],["Ruby","Ruby"],["Python","Python"]]
  .form-group
    = f.label :"主な経験開発体制"
    = f.select :system_ex,[["-",""],["ウォーターフォールモデル","ウォーターフォールモデル"],["プロトタイピングモデル","プロトタイピングモデル"],["スパイラルモデル","スパイラルモデル"],["アジャイル開発モデル","アジャイル開発モデル"]]
  .form-group
    = f.label :"主なフレームワーク"
    = f.select :frame,[["-",""],["Ruby on Rails","Ruby on Rails"],["CakePHP","CakePHP"],["Spring","Spring"],["jQuiry","jQuiry"],["Bootstrap","Bootstrap"]]
  .form-group
    = f.label :"採用ページのURL"
    = f.text_area :adoption, class: 'form-control', id: 'company_adoption'

  = f.submit nil, class: 'btn btn-primay'

app/views/companys/show.html.slim
h1 Companys#show
p Find me in app/views/companys/show.html.slim